<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.oyzh1994</groupId>
        <artifactId>fx-base</artifactId>
        <version>1.3.6</version>
    </parent>

    <artifactId>easymysql</artifactId>
    <version>0.2.0</version>

    <properties>
        <mysql.version>9.4.0</mysql.version>
        <druid.version>1.2.27</druid.version>
    </properties>

    <dependencies>

        <!-- 存储模块 -->
        <dependency>
            <groupId>io.github.oyzh1994</groupId>
            <artifactId>base-store</artifactId>
        </dependency>

        <!-- 事件模块 -->
        <dependency>
            <groupId>io.github.oyzh1994</groupId>
            <artifactId>base-event</artifactId>
        </dependency>

        <!-- i18n模块 -->
        <dependency>
            <groupId>io.github.oyzh1994</groupId>
            <artifactId>base-i18n</artifactId>
        </dependency>

        <!-- ssh模块 -->
        <dependency>
            <groupId>io.github.oyzh1994</groupId>
            <artifactId>base-ssh</artifactId>
        </dependency>

        <!-- fx-终端模块 -->
        <dependency>
            <groupId>io.github.oyzh1994</groupId>
            <artifactId>fx-terminal</artifactId>
        </dependency>

        <!-- fx-终端模块 -->
        <dependency>
            <groupId>io.github.oyzh1994</groupId>
            <artifactId>fx-editor</artifactId>
        </dependency>

        <!-- &lt;!&ndash; fx-终端模块 &ndash;&gt; -->
        <!-- <dependency> -->
        <!--     <groupId>io.github.oyzh1994</groupId> -->
        <!--     <artifactId>fx-rich</artifactId> -->
        <!-- </dependency> -->

        <!-- &lt;!&ndash; 加密工具类库 &ndash;&gt; -->
        <!-- <dependency> -->
        <!--     <groupId>cn.hutool</groupId> -->
        <!--     <artifactId>hutool-crypto</artifactId> -->
        <!--     <version>${hutool.version}</version> -->
        <!-- </dependency> -->

        <!-- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${mysql.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.alibaba/druid -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>${druid.version}</version>
        </dependency>

        <!-- Apache POI -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>${poi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${poi.version}</version>
        </dependency>

        <!-- 内存数据库 -->
        <!-- https://mvnrepository.com/artifact/com.h2database/h2 -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
